apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  POSTGRES_DB: taskflow_db
  POSTGRES_USER: seyha
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskflow_db
  SPRING_DATASOURCE_USERNAME: seyha
  SPRING_RABBITMQ_HOST: rabbitmq
---
apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  namespace: taskflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: seyha123
  SPRING_DATASOURCE_PASSWORD: seyha123
  SECURITY_JWT_SECRET_KEY: "c2V5aGEtdGFza2Zsb3ctc3VwZXItc2VjcmV0LWtleS0yMDI2LXZlcnktbG9uZw=="
